name: ฺฏุฒุงุฑุด ุจุงฺฏ ๐
description: ูุดฺฉู ุฏุฑ ุนููฺฉุฑุฏ ูพุฑูฺู ูพุฏุง ฺฉุฑุฏุฏุ ูุทูุงู ุงู ูุฑู ุฑู ูพุฑ ฺฉูุฏ.
title: "[ุจุงฺฏ] ฺฉ ุนููุงู ฺฉูุชุงู ุจุฑุง ูุดฺฉู ุจููุณุฏ"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ุณูุงู ู ููููู ุจุงุจุช ฺฏุฒุงุฑุด ูุดฺฉู ๐  
        ูุทูุงู ูุฑู ุฒุฑ ุฑู ุฏูู ูพุฑ ฺฉู ุชุง ุจุชููู ุณุฑุนโุชุฑ ูพฺฏุฑ ฺฉูู.

  - type: textarea
    id: bug_description
    attributes:
      label: ุดุฑุญ ูุดฺฉู
      description: ุฏููุงู ฺู ูุดฺฉู ุฑุฎ ุฏุงุฏูุ ูุทูุงู ูุงุถุญ ุชูุถุญ ุจุฏู.
      placeholder: ูุซูุงู ููุช ุฑู ุฏฺฉูู ฺฉูฺฉ ูโฺฉููุ ูฺ ุงุชูุงู ููโุงูุชู.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: ูุฑุงุญู ุจุงุฒุชููุฏ ูุดฺฉู
      description: ูุฑุญูู ุจู ูุฑุญูู ุจููุณ ฺุทูุฑ ุงู ูุดฺฉู ุฑุฎ ุฏุงุฏู.
      placeholder: |
        1. ูพุฑูฺู ุฑู ฺฉููู ฺฉุฑุฏู
        2. ุจุง python main.py ุงุฌุฑุง ฺฉุฑุฏู
        3. ุตูุญู ุณูุฏ ูููุฏ ู ุฎุทุง ูุดูู ูุฏุงุฏ
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ุงูุชุธุงุฑ ุฏุงุดุช ฺู ุงุชูุงู ุจูุชูุ
      placeholder: ูุซูุงู ุงูุชุธุงุฑ ุฏุงุดุชู ูพุงู ููููุช ฺุงูพ ุจุดู ุง ุตูุญู ุจุงุฑฺฏุฐุงุฑ ุจุดู.

  - type: textarea
    id: screenshots
    attributes:
      label: ุงุณฺฉุฑูโุดุงุช (ุงุฎุชุงุฑ)
      description: ุงฺฏุฑ ูโุชููุ ู ุนฺฉุณ ุงุฒ ูุดฺฉู ุจุฐุงุฑ.

  - type: input
    id: system_info
    attributes:
      label: ุณุณุชู ุนุงูู ู ูุณุฎู
      placeholder: ูุซูุงู ููุฏูุฒ ฑฐ ุง ูููฺฉุณ ุงูุจููุชู ฒฒ

  - type: input
    id: version_info
    attributes:
      label: ูุณุฎู ูพุงุชูู ุง ูุฑูุฑฺฏุฑ (ุฏุฑ ุตูุฑุช ูุงุฒ)
      placeholder: ูุซูุงู: Python 3.11 ุง Chrome 117

  - type: checkboxes
    id: terms
    attributes:
      label: ุดุฑุงุท ุงุฑุณุงู
      options:
        - label: ุจุฑุฑุณ ฺฉุฑุฏู ฺฉู ุงู ูุดฺฉู ูุจูุงู ฺฏุฒุงุฑุด ูุดุฏู
          required: true
